#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.05 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfffb;
constexpr uint24_t FX_DATA_BYTES = 1028;

namespace images8x8_FX
{
  constexpr uint24_t Hero8x8_frame0 = 0x000000;
  constexpr uint16_t Hero8x8_frame0_width  = 8;
  constexpr uint16_t Hero8x8_frame0_height = 8;

  constexpr uint24_t Hero8x8_frame1 = 0x000014;
  constexpr uint16_t Hero8x8_frame1_width  = 8;
  constexpr uint16_t Hero8x8_frame1_height = 8;

  constexpr uint24_t Hero8x8_frame2 = 0x000028;
  constexpr uint16_t Hero8x8_frame2_width  = 8;
  constexpr uint16_t Hero8x8_frame2_height = 8;

  constexpr uint24_t Banner = 0x00003C;
  constexpr uint16_t BannerWidth  = 106;
  constexpr uint16_t BannerHeight = 18;

  constexpr uint24_t BannerMask = 0x00017E;
  constexpr uint16_t BannerMaskWidth  = 106;
  constexpr uint16_t BannerMaskHeight = 24;

  constexpr uint24_t MonopixelMask = 0x0003FE;
  constexpr uint16_t MonopixelMaskWidth  = 1;
  constexpr uint16_t MonopixelMaskHeight = 8;

}

